WIP

diff --git a/.ci_cd/aws/cloudformation-create-ssm-document.yml b/.ci_cd/aws/cloudformation-create-ssm-document.yml
--- a/.ci_cd/aws/cloudformation-create-ssm-document.yml
+++ b/.ci_cd/aws/cloudformation-create-ssm-document.yml
@@ -5,20 +5,16 @@
 # ---------------------------------------------------------------------------------------------------------------------
 
 AWSTemplateFormatVersion: '2010-09-09'
-Description: 'Creates an SSM Document for attaching/detaching the EBS volume'
-
+Description: 'Creates SSM documents for attaching/detaching the EBS data volume'
 Parameters:
-  Host:
-    Description: FQDN for host.
-    Type: String
   InstanceId:
-    Description: InstanceId where the script needs to be executed.
+    Description: Instance ID where the script needs to be executed.
     Type: String
   VolumeId:
-    Description: VolumeId that needs to be attached/detached.
+    Description: Volume ID that needs to be attached/detached.
     Type: String
   EBSDeviceName:
-    Description: EBS DeviceName where this volume is mounted on.
+    Description: EBS Device name where this volume is mounted on.
     Type: String
 
 Resources:
@@ -27,19 +23,19 @@ Resources:
     Properties:
          Content:
             schemaVersion: '2.2'
-            description: 'Script for detaching the EBS volume'
+            description: 'Script for detaching the EBS data volume'
             parameters:
               InstanceId:
                 type: String
-                description: InstanceId where the script needs to be executed.
+                description: Instance ID where the script needs to be executed.
                 default: !Ref InstanceId
               VolumeId:
                 type: String
-                description: VolumeId that needs to be detached.
+                description: Volume UD that needs to be detached.
                 default: !Ref VolumeId
               EBSDeviceName:
                   type: String
-                  description: EBS DeviceName where this volume is mounted on.
+                  description: EBS Device name where this volume is mounted on.
                   default: !Ref EBSDeviceName
             mainSteps:
               - name: StopDocker
@@ -70,13 +66,15 @@ Resources:
                 inputs:
                   runCommand: 
                     - |
-                      VOLUME=$(aws ec2 detach-volume --volume-id {{ VolumeId }})
+                      VOLUME=$(aws ec2 detach-volume --volume-id {{ VolumeId }} 2>/dev/null)
                       STATUS=$(aws ec2 describe-volumes --query "Volumes[?VolumeId=='{{ VolumeId }}'].State" --output text 2>/dev/null)
                       
-                      while [[ "$STATUS" == 'in-use' ]] do
-                        echo "Volume is still in-use .. Sleeping 30 seconds"
+                      count=0
+                      while [[ "$STATUS" == 'in-use' ]] && [[ $count -lt 30 ]] do
+                        echo "Volume is still detaching .. Sleeping 30 seconds"
                         sleep 30
                         STATUS=$(aws ec2 describe-volumes --query "Volumes[?VolumeId=='{{ VolumeId }}'].State" --output text 2>/dev/null)
+                        count=$((count+1))
                       done
 
                       if [ "$STATUS" != "available" ]; then
@@ -87,26 +85,26 @@ Resources:
          TargetType: /AWS::EC2::Instance
          UpdateMethod: Replace
          DocumentType: Command
-         Name: !Sub ${Host}_detach
+         Name: detach_volume
   
   SSMAttachEBSDocument:
     Type: AWS::SSM::Document
     Properties:
          Content:
             schemaVersion: '2.2'
-            description: 'Script for attaching the EBS volume'
+            description: 'Script for attaching the EBS data volume'
             parameters:
               InstanceId:
                 type: String
-                description: InstanceId where the script needs to be executed.
+                description: Instance ID where the script needs to be executed.
                 default: !Ref InstanceId
               VolumeId:
                 type: String
-                description: VolumeId that needs to be attached.
+                description: Volume UD that needs to be attached.
                 default: !Ref VolumeId
               EBSDeviceName:
                   type: String
-                  description: EBS DeviceName where this volume needs to be mounted on.
+                  description: EBS Device name where this volume needs to be mounted on.
                   default: !Ref EBSDeviceName
             mainSteps:
               - name: StopDocker
@@ -114,17 +112,46 @@ Resources:
                 inputs:
                   runCommand:
                     - systemctl stop docker
-              - name: MountVolume
+              - name: AttachVolume
                 action: aws:runShellScript
                 inputs:
-                  runCommand:
-                    - mount {{ EBSDeviceName }} /var/lib/docker/volumes
+                  runCommand: 
+                    - |
+                      VOLUME=$(aws ec2 attach-volume --volume-id {{ VolumeId }} --instance-id {{ InstanceId }} --device {{ EBSDeviceName }} 2>/dev/null)
+                      STATUS=$(aws ec2 describe-volumes --query "Volumes[?VolumeId=='{{ VolumeId }}'].State" --output text 2>/dev/null)
+                      
+                      count=0
+                      while [[ "$STATUS" == 'available' ]] && [ $count -lt 30 ]; do
+                        echo "Volume is still attaching .. Sleeping 30 seconds"
+                        sleep 30
+                        STATUS=$(aws ec2 describe-volumes --query "Volumes[?VolumeId=='{{ VolumeId }}'].State" --output text 2>/dev/null)
+                        count=$((count+1))
+                      done
+
+                      if [ "$STATUS" != 'in-use' ]; then
+                        echo "Volume attaching failed with status $STATUS"
+                        exit 1
+                      else
+                        echo "Volume successfully attached"
+                      fi
+              - name: PrepareVolume
+                action: aws:runShellScript
+                inputs:
+                  runCommand: 
+                    - |
+                      FILESYSTEM=$(blkid -o value -s TYPE {{ EBSDeviceName }})
+                      if [ -z "$FILESYSTEM" ]; then
+                        mkfs -t xfs {{ EBSDeviceName }}
+                        mount {{ EBSDeviceName }} /var/lib/docker/volumes
+                      else
+                        mount {{ EBSDeviceName }} /var/lib/docker/volumes
+                      fi
               - name: AddFstabEntry
                 action: aws:runShellScript
                 inputs:
                   runCommand:
                     -  |
-                       UUID=$(sudo blkid -o value -s UUID {{ EBSDeviceName }})
+                       UUID=$(blkid -o value -s UUID {{ EBSDeviceName }})
                        if [ -n "$UUID" ]; then
                           cp /etc/fstab /etc/fstab.orig
                           echo "UUID=$UUID /var/lib/docker/volumes xfs defaults,nofail 0 2" >> /etc/fstab
@@ -141,4 +168,4 @@ Resources:
          TargetType: /AWS::EC2::Instance
          UpdateMethod: Replace
          DocumentType: Command
-         Name: !Sub ${Host}_attach
+         Name: attach_volume
